title = "covid19 PyTorch"

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = "3"
loadpretrainedmodel = true
random_seed = true
pretrainedmodelpath = 'weights/model_3cls_gender.pt'
use_3d = false
use_lstm=false
use_slice=true
use_plus=true
mod='co'#'ab
class_num=2

[input]
batchsize = 32
numworkers = 8
shuffle = true

[model]
type = "Finetune-label"
inputdim = 256
hiddendim = 256
numclasses = 2
numlstms = 2

[training]
train = true
epochs = 80
startepoch = 0
statsfrequency = 1000
data_root = 'all_ages_genders.txt'#useless and used as ages_gender.txt path
index_root = 'data/txt/train2cls_pos.txt'
padding = 45
learningrate = 1e-5
momentum = 0.95
weightdecay = 0.05
save_prefix = "weights/cap_vs_covid"

[validation]
validate = true
data_root = 'all_ages_genders.txt'
index_root = 'data/txt/test2cls_pos.txt'
padding = 45
saveaccuracy = false


[test]
test = false
data_root = '/mnt/data6/lung_jpgs_with_SEG'
index_root = 'data/txt/2train_lidc_ild_train.txt'
padding = 45
saveaccuracy = false
