title = "covid19 PyTorch test"

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = "1"
loadpretrainedmodel = true
random_seed = true
use_3d = false
use_lstm=false
use_slice=true
use_plus=false
use25d=false
class_num=3
plus_as_input=false
mod='co'
R=1
radiomics_path='/mnt/data9/r_c_cache'

[input]
batchsize = 32
numworkers = 8
shuffle = true

[model]
type = "Finetune-label"
inputdim = 256
hiddendim = 256
numclasses = 2
numlstms = 2

[training]
train = true
epochs = 50
startepoch = 0
statsfrequency = 1000
data_root = 'all_ages_genders.txt'#useless and used as ages_gender.txt path
index_root = 'data/txt/train5cls.txt'
padding = 35
learningrate = 1e-5
momentum = 0.95
weightdecay = 0.05
save_prefix = "weights/model_5cls"

[validation]
validate = true
data_root = 'all_ages_genders.txt'
index_root = 'data/txt/test5cls.txt'
padding = 35
saveaccuracy = false


[test]
test = false
data_root = 'radiomics/r_features.csv'
index_root = 'data/txt/2train_lidc_ild_train.txt'
padding = 100
saveaccuracy = false
